server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  cloud:
    config:
      enabled: false
  application:
    name: order-gateway
logging:
  level:
    root: debug




